name: darwin_http_gen
description: Code generator for the http package of the darwin framework
version: 1.1.0-alpha.16
repository: https://github.com/DarwinFramework/darwin

environment:
  sdk: '>=2.18.3 <3.0.0'

dependencies:
  build: '>=2.0.0 <3.0.0'
  analyzer: ">=2.0.0 <6.0.0"
  source_gen: '>=1.0.0 <=2.0.0'
  collection: '>=1.15.0 <2.0.0'
  crypto: '>=3.0.0 <4.0.0'
  glob: '>=2.0.0 <3.0.0'
  path: '>=1.8.0 <2.0.0'

  code_builder: '>=4.3.0 <5.0.0'
  dart_style: '>=2.2.4 <3.0.0'

  lyell: ^0.0.2
  lyell_gen: ^0.2.0

  darwin_sdk: ^1.1.0-alpha.11
  darwin_injector: ^1.1.0-alpha.1
  darwin_eventbus: ^1.1.0-alpha.3
  darwin_marshal: ^1.1.0-alpha.12
  darwin_gen: ^1.1.0-alpha.11
  darwin_http: ^1.1.0-alpha.15
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
