name: darwin_project
repository: https://github.com/DarwinFramework/darwin
packages:
  - sdk/**
scripts:
  copy-readme:
    name: copy-readme
    description: 'Copies the root-Readme to the darwin_sdk package'
    run: cp README.md sdk/darwin/README.md
  analyze:
    name: analyze
    description: 'Runs the dart analyzer'
    run: dart analyze .
    exec:
      concurrency: 1
  format:
    name: format
    description: 'Runs the dart fromatter'
    run: dart format .
    exec:
      concurrency: 1
