name: darwin_http
description: Http server and rest api functionality for the darwin framework
version: 1.1.0-alpha.10
repository: https://github.com/DarwinFramework/darwin

environment:
  sdk: '>=2.18.3 <3.0.0'

dependencies:
  shelf: ^1.4.0
  logging: ^1.1.0
  meta: ^1.8.0
  darwin_sdk: ^1.1.0-alpha.7
  darwin_injector: ^1.1.0-alpha.1
  darwin_eventbus: ^1.1.0-alpha.3
  darwin_marshal: ^1.1.0-alpha.8
  conduit_open_api: ^4.1.8

  lyell: ^0.0.2
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
