name: darwin_http
description: A starting point for Dart libraries or applications.
version: 1.1.0-alpha.4
repository: https://github.com/DarwinFramework/darwin

environment:
  sdk: '>=2.18.3 <3.0.0'

dependencies:
  shelf: ^1.4.0
  logging: ^1.1.0
  meta: ^1.8.0
  darwin_sdk: ^1.1.0-alpha.2
  darwin_injector: ^1.1.0-alpha.0
  darwin_eventbus: ^1.1.0-alpha.0
  darwin_marshal: ^1.1.0-alpha.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
