name: darwin_http
description: A starting point for Dart libraries or applications.
version: 1.1.0-alpha.1
repository: https://github.com/DarwinFramework/darwin

environment:
  sdk: '>=2.18.3 <3.0.0'

dependencies:
  shelf: 1.4.0
  logging: ^1.1.0
  meta: ^1.8.0
  darwin_sdk: ^1.1.0-alpha.1
  darwin_injector: ^1.1.0-alpha.0
  darwin_eventbus: ^1.1.0-alpha.0
  darwin_marshal: ^1.1.0-alpha.1
dependency_overrides:
  darwin_sdk:
    path: ../darwin
  darwin_injector:
    path: ../darwin_injector
  darwin_eventbus:
    path: ../darwin_eventbus
  darwin_marshal:
    path: ../darwin_marshal

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
