name: darwin_eventbus
description: Synchronous and asynchronous eventbus implementations used by the drawin framework
version: 1.1.0-alpha.1
repository: https://github.com/DarwinFramework/darwin

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
