name: smoke_test_0
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  logging: '>=1.1.0 <1.2.0'
  darwin_sdk:
    path: ../../sdk/darwin
  darwin_injector:
    path: ../../sdk/darwin_injector
  darwin_eventbus:
    path: ../../sdk/darwin_eventbus
  darwin_http:
    path: ../../sdk/darwin_http
  darwin_marshal:
    path: ../../sdk/darwin_marshal

dev_dependencies:
  build_runner: any
  darwin_gen:
    path: ../../sdk/darwin_gen
  darwin_http_gen:
    path: ../../sdk/darwin_http_gen

  lints: ^2.0.1
  test: ^1.23.1

dependency_overrides:
  darwin_sdk:
    path: ../../sdk/darwin
  darwin_injector:
    path: ../../sdk/darwin_injector
  darwin_eventbus:
    path: ../../sdk/darwin_eventbus
  darwin_marshal:
    path: ../../sdk/darwin_marshal
  darwin_gen:
    path: ../../sdk/darwin_gen
  darwin_http:
    path: ../../sdk/darwin_http
