name: darwin_test
description: A simple test library for the darwin framework
version: 1.1.0-alpha.11
repository: https://github.com/DarwinFramework/darwin

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  path: ^1.8.0
  darwin_sdk: ^1.1.0-alpha.10
  darwin_injector: ^1.1.0-alpha.1
  darwin_http: ^1.1.0-alpha.14
  test: ^1.16.0
  logging: ^1.1.0
  collection: ^1.17.1
  shelf: ^1.4.0
dev_dependencies:
  lints: ^2.0.0
