name: darwin_sdk
description: A sample command-line application.
version: 1.1.0-alpha.2
repository: https://github.com/DarwinFramework/darwin

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  path: '>=1.8.0 <1.9.0'
  logging: '>=1.1.0 <1.2.0'
  ansi_styles: '>=0.3.1 <0.4.0'
  meta: ^1.8.0

  darwin_injector: ^1.1.0-alpha.0
  darwin_eventbus: ^1.1.0-alpha.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
