name: darwin_sdk
description: Swiss army knife for creating service based applications in dart, using IoC and a powerful annotation based code generator
version: 1.1.0-alpha.5
repository: https://github.com/DarwinFramework/darwin

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  path: '>=1.8.0 <1.9.0'
  logging: '>=1.1.0 <1.2.0'
  ansi_styles: '>=0.3.1 <0.4.0'
  meta: ^1.8.0

  darwin_injector: ^1.1.0-alpha.1
  darwin_eventbus: ^1.1.0-alpha.1
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  darwin_test: ^1.1.0-alpha.5