name: darwin_starter
description: A project generator for darwin framework applications
version: 0.0.1-alpha.1
repository: https://github.com/DarwinFramework/darwin

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  dio: ^4.0.0
  crypto: ^3.0.1
  archive: ^3.1.2
  glob: ^2.1.1
  mustache_template: ^2.0.0

  toml: ^0.13.1
  yaml: ^3.1.1
  yaml_writer: ^1.0.3
  json2yaml: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
