name: darwin_marshal
description: A starting point for Dart libraries or applications.
version: 1.1.0-alpha.2
repository: https://github.com/DarwinFramework/darwin

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  path: ^1.8.0
  darwin_sdk: ^1.1.0-alpha.2
  darwin_injector: ^1.1.0-alpha.0
  darwin_eventbus: ^1.1.0-alpha.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
