name: charles
description: Commandline utility for the darwin framework.
version: 0.0.1-alpha.3
repository: https://github.com/DarwinFramework/darwin

environment:
  sdk: '>=2.18.6 <3.0.0'

executables:
  charles:

dependencies:
  path: ^1.8.0
  cli_util: ^0.3.5
  uuid: ^3.0.4
  args: ^2.3.2
  dio: ^4.0.0
  crypto: ^3.0.1
  archive: ^3.1.2
  glob: ^2.1.1
  mustache_template: ^2.0.0
  pub_api_client: ^2.4.0
  toml: ^0.13.1

  darwin_starter: ^0.0.1-alpha.4
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
