name: all_packages
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Run Smoke Tests"
        run: melos run smoke

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Run Tests"
        run: melos test --no-select
